### ISSUE TITLE
Troubles styling with CSS

### ISSUE THREAD

**Issue by Azakidev** [BoxFactura/pulltorefresh.js#127]
Hello, I'm trying to override some styles for the text in the CSS file, but it seems to be ignoring it
I have looked around in the site and the repository but I have not been able to find documentation on overriding styles with CSS anywhere.

I'm assuming I'm doing something wrong, since I honestly don't know what I'm doing, I'm new to programming.
Could I be given an example on how to do this?

Here's my style.css:

``` css
/* . . . */

.ptr--ptr {
    box-shadow: inset 0 -3px 5px rgba(255, 255, 255, 0.12);
}
.ptr--text {
    color: var(--ptr-color);
}
.ptr--arrow {
    color: var(--ptr-color);
}

/* . . . */
```
My PullToRefresh.init call
```js
/* . . . */

PullToRefresh.init({
            mainElement: '#wrapper',
            distThreshold: 100,
            distMax: 110,
            distReload: 90,
        
            onRefresh:  /* . . . */
            }
        });

/* . . . */
```

And my index.html
```html
<head>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div id="wrapper">
        <h1><h1>
        <h2><h2>
        <div></div>
    </div>
    <script src="bundle.js"></script>
</body>
```

Thanks in advance!
